meta:
  environment: ~

  releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

  stemcell: (( merge ))

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge || meta.releases ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false

resource_pools:
  - network: default
    name: default
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
